// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To configure your actual project credentials:
/// 1. Run `npm install -g firebase-tools` if you haven't already.
/// 2. Run `firebase login` in your terminal.
/// 3. Run `dart pub global activate flutterfire_cli`.
/// 4. In this project directory, run: `flutterfire configure`
///
/// This will regenerate this file with the correct configurations for your Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebKey-1234567890abcdef',
    appId: '1:1234567890:web:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'notes-manager-dummy',
    authDomain: 'notes-manager-dummy.firebaseapp.com',
    storageBucket: 'notes-manager-dummy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBpKamRb4guNHhJGlTzb-izvQAfSMIHbo',
    appId: '1:949103120048:android:486726e919d3652f7c7575',
    messagingSenderId: '949103120048',
    projectId: 'notes-manager-a26b7',
    storageBucket: 'notes-manager-a26b7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXKoFqCGIOCcnFCfd0MIfsNozdVDuMPo',
    appId: '1:949103120048:ios:d1d62a783fb176d67c7575',
    messagingSenderId: '949103120048',
    projectId: 'notes-manager-a26b7',
    storageBucket: 'notes-manager-a26b7.firebasestorage.app',
    iosBundleId: 'com.notesmanager.notesManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyMacOSKey-1234567890abcdef',
    appId: '1:1234567890:ios:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'notes-manager-dummy',
    storageBucket: 'notes-manager-dummy.appspot.com',
    iosBundleId: 'com.notesmanager.notesManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyWindowsKey-1234567890abcdef',
    appId: '1:1234567890:windows:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'notes-manager-dummy',
    storageBucket: 'notes-manager-dummy.appspot.com',
  );
}
